## MARIAM BADURE-04
### 14//01/2026
### Practice of Major Functions in NumPy, Pandas, and Matplotlib Libraries.
### ML LAB
### EXP1
### PID-246002


### Program-1 to practice python numpy functions.

In [1]:
import numpy as np

In [2]:
# 1. Array Creation

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr1)


Array from list: [1 2 3 4 5]


In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr2)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [5]:
arr_arange = np.arange(0, 10, 2)
print("arange array:", arr_arange)

arange array: [0 2 4 6 8]


In [6]:
arr_linspace = np.linspace(0, 1, 5)
print("linspace array:", arr_linspace)

linspace array: [0.   0.25 0.5  0.75 1.  ]


In [7]:
arr_zeros = np.zeros((2,3))
print("zeros array:\n", arr_zeros)

zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr_ones = np.ones((3,2))
print("ones array:\n", arr_ones)

ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
arr_eye = np.eye(3)
print("Identity matrix:\n", arr_eye)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 2. Array Attributes

In [11]:
print("Shape of arr2:", arr2.shape)
print("Size of arr2:", arr2.size)
print("Number of dimensions:", arr2.ndim)
print("Data type:", arr2.dtype)
print("Item size (bytes):", arr2.itemsize)

Shape of arr2: (2, 3)
Size of arr2: 6
Number of dimensions: 2
Data type: int64
Item size (bytes): 8


In [12]:
# 3. Indexing and Slicing

In [13]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("Index 2:", arr[2])
print("Last element:", arr[-1])
print("Slice 1:4:", arr[1:4])

Original array: [10 20 30 40 50]
Index 2: 30
Last element: 50
Slice 1:4: [20 30 40]


In [14]:
# 2D array slicing

In [15]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n", arr2d)
print("First row:", arr2d[0,:])
print("Second column:", arr2d[:,1])
print("Submatrix:\n", arr2d[0:2,1:3])

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
Submatrix:
 [[2 3]
 [5 6]]


In [16]:
# 4. Basic Operations

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [18]:
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a ** 2:", a**2)

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a ** 2: [1 4 9]


In [19]:
# Broadcasting

In [20]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([1,1,1])
print("Broadcasting sum:\n", c + d)

Broadcasting sum:
 [[2 3 4]
 [5 6 7]]


In [21]:
# 5. Universal Functions (ufuncs)

In [22]:
arr = np.array([1,4,9,16])
print("sqrt:", np.sqrt(arr))
print("exp:", np.exp(arr))
print("log:", np.log(arr))
print("sin:", np.sin(arr))
print("cos:", np.cos(arr))

sqrt: [1. 2. 3. 4.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
log: [0.         1.38629436 2.19722458 2.77258872]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
cos: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [23]:
# 6. Aggregation Functions

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print("Sum:", np.sum(arr))
print("Sum axis 0:", np.sum(arr, axis=0))
print("Sum axis 1:", np.sum(arr, axis=1))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))

Sum: 21
Sum axis 0: [5 7 9]
Sum axis 1: [ 6 15]
Mean: 3.5
Max: 6


In [25]:
print("Min:", np.min(arr))
print("Argmax:", np.argmax(arr))
print("Argmin:", np.argmin(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))

Min: 1
Argmax: 5
Argmin: 0
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665


In [26]:
# 7. Reshaping and Flattening

In [27]:
arr = np.arange(12)
print("Original array:", arr)
arr_reshaped = arr.reshape(3,4)
print("Reshaped 3x4 array:\n", arr_reshaped)
arr_flat = arr_reshaped.flatten()
print("Flattened array:", arr_flat)
arr_transpose = arr_reshaped.T
print("Transpose:\n", arr_transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [28]:
# 8. Stacking and Splitting

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Horizontal stack:", np.hstack((a,b)))
print("Vertical stack:\n", np.vstack((a,b)))

Horizontal stack: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]


In [30]:
arr = np.arange(9)
print("Original array:", arr)
print("Split into 3 parts:", np.split(arr, 3))

Original array: [0 1 2 3 4 5 6 7 8]
Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [31]:
# 9. Copy vs View

In [32]:
arr = np.array([1,2,3,4])
arr_view = arr.view()
arr_copy = arr.copy()
arr_view[0] = 100
arr_copy[1] = 200
print("Original after view change:", arr)
print("Original after copy change:", arr)

Original after view change: [100   2   3   4]
Original after copy change: [100   2   3   4]


In [33]:
# 10. Boolean Indexing & Fancy Indexing

In [34]:
arr = np.array([10,20,30,40,50])
print("Elements > 25:", arr[arr>25])
indices = [0,2,4]
print("Fancy indexing:", arr[indices])

Elements > 25: [30 40 50]
Fancy indexing: [10 30 50]


In [35]:
# 11. Random Numbers

In [36]:
rand_arr = np.random.rand(3,3) # uniform [0,1)
print("Random array:\n", rand_arr)

Random array:
 [[0.07219221 0.35617701 0.16265003]
 [0.32585557 0.03970046 0.4252566 ]
 [0.78530926 0.27045733 0.08788924]]


In [37]:
rand_int = np.random.randint(0,10,5)
print("Random integers:", rand_int)

Random integers: [6 2 3 5 9]


In [38]:
normal_arr = np.random.randn(3,3) # standard normal
print("Normal distribution array:\n", normal_arr)

Normal distribution array:
 [[ 0.48882506 -0.59680446  0.29598385]
 [-1.491679    0.42750857  0.51995961]
 [ 1.70473399  0.19717075  1.00116117]]


In [39]:
# 12. Linear Algebra Functions

In [40]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [41]:
print("Matrix multiplication:\n", np.dot(A,B))
print("Matrix determinant:", np.linalg.det(A))
print("Matrix inverse:\n", np.linalg.inv(A))
print("Eigenvalues and Eigenvectors:\n", np.linalg.eig(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix determinant: -2.0000000000000004
Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and Eigenvectors:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [42]:
# 13. Saving and Loading Arrays

In [43]:
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

Loaded array: [10 20 30 40 50]


In [44]:
print("\nAll major NumPy functions executed successfully!")


All major NumPy functions executed successfully!
